
server:
  port: ${PORT:8085}
  url: ${SERVER_URL}

callback:
  url: ${CALLBACK_URL}

spring:
  forward-headers-strategy: framework
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # devben oké, prodban inkább validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.pgy.no-ip.hu/realms/pgy
stripe:
  api:
    secretKey: ${STRIPE_API_SECRET_KEY}
    webhookSigningSecret: ${STRIPE_API_WEBHOOK_SIGNING_SECRET}
  price:
    premiumId: ${STRIPE_PRICE_PREMIUM_ID}
